### ISSUE TITLE
Add the abilty to change the sprite of a character

### ISSUE THREAD

**Issue by aspiring-aster** [tfjoek/class-of-09-scene-generator#1]
I can tackle this if you want. Just something where each character has a folder of sprites and once you placed a character, you can switch the sprite of them.

**Comment by tfjoek** [comment]
i was thinking that the best way to handle all the different sprites would go:

initial character dropdown shows just the character -> then after you chose a character then you can change the clothes/expression of the character you picked
![image](https://github.com/user-attachments/assets/6c1ee762-2b54-46e3-b601-29ed293169af)
theres a shit ton of them for main characters

**Comment by aspiring-aster** [comment]
So here's what I have so far done, I have a select that shows up after you place a character and that select will sync with the current selected character to select the current outfit. Only problem is that each character has a different amount of outfits. I don't want this feature to be too intrusive to the codebase. 

Do you think it will be okay if I make some sort of JSON that hard codes the counts of different outfits for each character and use that JSON to determine how many select options to make for a character?

I just don't want to butt in and try to make the repo fit the new feature.

https://github.com/user-attachments/assets/365bb67c-e24c-46a0-abd6-a05505ce2b96

**Comment by aspiring-aster** [comment]
Here's how the select menu looks like since OBS doesn't capture it for some reason.
![select](https://github.com/user-attachments/assets/087cc734-aefe-4f32-b621-85fb9fd2fecc)

**Comment by aspiring-aster** [comment]
I'll stop yapping and coding after this, maybe I can have a button like "Placement" that opens up the modal and it will display every character and by every character is a select for their outfits? This seems to make the most sense then changing the outfit of the character selected by the character-select who might be in the scene or not. 

Doing it a similar way will only let you pick outfits for characters in the scene just like how Placement works.
![outfits](https://github.com/user-attachments/assets/e263cf32-2722-4445-80d8-c582a643f436)

**Comment by tfjoek** [comment]
![kuva](https://github.com/user-attachments/assets/3f4754af-2e66-42d2-8a2e-ddc93ef9e31d)
you mean like this? also renaming the placement menu to like character settings could be more logical

**Comment by tfjoek** [comment]
> Do you think it will be okay if I make some sort of JSON that hard codes the counts of different outfits for each character and use that JSON to determine how many select options to make for a character?

yeah 

> I don't want this feature to be too intrusive to the codebase.

shit is scuffed already LOL

**Comment by aspiring-aster** [comment]
I wouldn't mind renaming the placement menu to be a character settings and handle both the placement of a character and the outfit for every placed character. I'll look into making a basic JSON "database" that's fetched just to get hard coded info so I know basic stuff like how many outfits a character has.

**Comment by aspiring-aster** [comment]
Should be sometime within the next 10 hours. Sorry, I just took Friday and Thursday off from any coding

**Comment by tfjoek** [comment]
yeah np dont worry lol just wanted to hear ur alive still

**Comment by aspiring-aster** [comment]
I needed a break from coding since I'm in school, I code for work, and I sometimes have to teach coding due to being a TA in addition to being a part-time react dev lol

PR is made, my code is alright. Don't be afraid to be brutally honest and tell me it sucks and I need to fix it. Here's the [PR](https://github.com/tfjoek/class-of-09-scene-generator/pull/5).

**Comment by tfjoek** [comment]
yeah im a student aswell no worries this is just a fun project :) ill take a look at it when im home

**Comment by aspiring-aster** [comment]
I wouldn't mind at least trying to help out if you attempt to be crazy and port it to React. I like helping out the best I can with cool stuff like this! Even if I'm only a weekend warrior with this stuff!
